if(EXISTS "/mnt/g/Uni/Cpp Molecular Dynamics/hpcMolecularDynamics/notes_lecture/tests/my_tests[1]_tests.cmake")
  include("/mnt/g/Uni/Cpp Molecular Dynamics/hpcMolecularDynamics/notes_lecture/tests/my_tests[1]_tests.cmake")
else()
  add_test(my_tests_NOT_BUILT my_tests_NOT_BUILT)
endif()
